"""Add skills and education to JobOffer

Revision ID: 74a835eeaadb
Revises: c8cb69f0ca9e
Create Date: 2026-01-02 21:11:54.052084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a835eeaadb'
down_revision = 'c8cb69f0ca9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.drop_column('education')
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
